### ISSUE TITLE
Re-render issues

### ISSUE THREAD

**Issue by HaNdTriX** [Swizec/useAuth#10]
Please note that the following code will cause a re-render of your entire subtree.

https://github.com/Swizec/useAuth/blob/ef4a9d46d1045565414a7f9143371be6b222f8b5/src/AuthProvider.js#L53-L59

> Because context uses reference identity to determine when to re-render, there are some gotchas that could trigger unintentional renders in consumers when a provider’s parent re-renders. 

https://reactjs.org/docs/context.html#caveats

## Possible solutions to this problem

1. Use a class component and lift your context into `this.state`
2. Use `React.useMemo()`

**Comment by Swizec** [comment]
Ah yes forgot about that. Should be an easy fix. Thanks for flagging!

**Comment by Swizec** [comment]
@all-contributors add @HaNdTriX for bug

**Comment by Swizec** [comment]
@all-contributors add @HaNdTriX for bug

**Comment by Swizec** [comment]
Thanks for your bug report @HaNdTriX the issue has been resolved in v0.4.1. Just published :)
