### ISSUE TITLE
useAuth Docs v2 - Another Idea (Theme-UI)

### ISSUE THREAD

**Issue by erichodges** [Swizec/useAuth#103]
Hi Swizec,

I set up a new Gatsby site using Theme-ui for the docs. I think it's better than my earlier effort. I didn't set up the useAuth login as it seems that you are still working on refactoring and expanding login provider options. Happy to set it up later. :-)

https://use-auth-docs.vercel.app/

https://github.com/erichodges/useAuthDocs

**Comment by Swizec** [comment]
My dude @erichodges I love this! Sorry it took me so long to reply; time flies 😅

I want to get the new site up in time for Reactathon on Monday. Do you mind if I fully steal what you've build? 
With contribution of course :)

Think I'd copy your repo into the /examples directory and add the new useAuth integration. Or I can fork off your repo if you prefer.

**Comment by erichodges** [comment]
Hi Swizec, no worries, I know you're busy. Yeah, since I didn't add the new code and get that working, it would be a lot faster for you to do it. Up to you how you want to set that up. It would be great to get a bit of promotion at Reactathon no matter how small. I'm looking for work :-). I can then also add it to my portfolio as a live project which would be awesome!

**Comment by Swizec** [comment]
Closing because this is now the new docs page :)

Further contributions super welcome. There's a couple small css issues here and there
