### ISSUE TITLE
Access token of logged in user

### ISSUE THREAD

**Issue by jackfranklin** [Swizec/useAuth#11]
I'm using Auth0 to allow users to login via GitHub. 

I now need to get at the OAuth token from GitHub so I can make authorised requests to the GitHub API. I think maybe `useAuth` could expose this token too, if it can? (I'm not super familiar with auth0 so sorry if I'm heading down the wrong path here).

This library made auth so much easier so thank you for that!

**Comment by bluematter** [comment]
@jackfranklin Just in time. I also need to obtain the id_token to add into the headers of my requests to graphcool.

Would be nice to document this and expose the token.

I wonder if the cookie that was stored and parsed into a token? Ill look into that.

**Comment by NWRichmond** [comment]
@jackfranklin @bluematter 
I haven't tried it, but you might be able to accomplish that by creating an [Auth0 Rules function](https://auth0.com/video-tutorials/advanced-usage-of-auth0/using-rules). The video in the link explains how to implement custom logic such that, "...you could easily change this to query one of your databases **or make an API call to an external server** as needed."

**Comment by puregarlic** [comment]
@bluematter @jackfranklin I've made some changes to a local version of `useAuth` that exposes both `id_token` and `access_token`; I'll get a PR up soon for discussion.

**Comment by Swizec** [comment]
@jackfranklin @NWRichmond @puregarlic @bluematter just published version 0.4.0, which exposes the full `authResult` object which contains your accessToken and idToken ✌️

https://github.com/Swizec/useAuth#users-access-tokens
