### ISSUE TITLE
Bug?: Project does not just run with the desired Auth Client, it is asking to install the other auth client

### ISSUE THREAD

**Issue by vacom** [Swizec/useAuth#115]
In the project I am testing (NextJS) I am using Auth0 Auth Client but the project does not run because it is asking for the other Auth Client **netlify-identity-widget.**

When installing everything works again correctly but in this case, I don't need the Netlify package

"react-use-auth": "^1.0.0",

```javascript
Error: Module not found: Can't resolve 'netlify-identity-widget'
```

**Comment by Swizec** [comment]
Yes this is a bug, nice find! I'm working on a fix and having some trouble with code splitting.

Got any ideas?

**Comment by Swizec** [comment]
@vacom this has been fixed. Install 2.0.0 and change your Auth0 import to `import { Auth0 } from 'react-use-auth/auth0'
