### ISSUE TITLE
Persist login status on refresh

### ISSUE THREAD

**Issue by omonk** [Swizec/useAuth#21]
Love this module, so easy to integrate and work with, just wondering one thing:

From what I can tell this should persist the user being logged in between refreshes or am I being slow? It's logging out user between refreshes, localStorage values still present...

**Comment by multicam** [comment]
same here :)

**Comment by omonk** [comment]
Seems like something isn't working on the auth0 side, the module returns an error. Need to do some more investigation

**Comment by omonk** [comment]
Seems like we're not the only ones dealing with this issue: 

- On community chat [here](https://community.auth0.com/t/checksession-always-return-login-required-on-localhost/22119/19) - a huge thread about persisting login
- On a walkthrough [here](https://auth0.com/blog/react-tutorial-building-and-securing-your-first-app/), if you search the page for `Keeping Users Signed In after a Refresh` it'll take you to the bottom of the page you find a section detailing having to register the app with whichever provider (in the example and my case, google) you're using.

Going to try this out and will report back

**Comment by omonk** [comment]
Tadaaaa it works 💃 

Will open a PR to update README to give some brief details around the steps required!

**Comment by Swizec** [comment]
Thanks so much for your help and research @omonk
