### ISSUE TITLE
App uses localStorage for storing tokens

### ISSUE THREAD

**Issue by graysonhicks** [Swizec/useAuth#3]
Using `localStorage` for storing auth0 tokens is not considered best practice [per their docs](https://auth0.com/docs/security/store-tokens#don-t-store-tokens-in-local-storage).  Instead, they recommend using the [checkSession](https://auth0.com/docs/libraries/auth0js/v9#using-checksession-to-acquire-new-tokens) method if no back-end is available.

**Comment by Swizec** [comment]
This is now fixed. Thanks for the heads up @graysonhicks
