### ISSUE TITLE
Regular js react app asking for typescript declarations

### ISSUE THREAD

**Issue by b2times4** [Swizec/useAuth#33]
Bear with me as I just got started with React.
Installed module through yarn 

```yarn add react-use-auth ```

Immediately when I slap 

``` import { useAuth } from "react-use-auth"; ```

 in my index.js file I get a little warning on that line stating:

```
Could not find a declaration file for module 'react-use-auth'. '/Users/<omitted>/SERVER/with-apollo/with-apollo-npm/node_modules/react-use-auth/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-use-auth` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-use-auth';`ts(7016)
```

Unsure why it is asking for typescript declarations - I thought I was doing everything in plain JS.
I thought that this was just a warning and this would not affect the functioning of the module but, while running the actual app I got a warning stating:

```TypeError: Cannot read property 'state' of null```

At this line:

```const Login = () => {
  const { isAuthenticated, login, logout, isAuthenticating, user } = useAuth()
```

What I did to make sure that it becomes more plausible that the typescript warning above is causing this is the following 'reverse engineering' procedure I followed:

I copied all the files from this module into my 'local' filesystem (lib folder) and called them this way - in stead of via the node_modules dir.

**Result**: The typescript error went away and I no longer have the Cannot read property 'state' of null error anymore.
What's better : the login procedure works. I can log in and log out.

**Comment by Swizec** [comment]
Hey @b2times4 thannks for reporting this, looks like it's been resolved at some point since September 18th. Current version 0.5.1 doesn't show any type errors in a basic CRA app.

You can look at how it's done in the examples directory. I didn't change anything except the version number :)

**Comment by Swizec** [comment]
@all-contributors add @b2times4 for issues
