### ISSUE TITLE
Potential read obsolete state contextValue

### ISSUE THREAD

**Issue by sophister** [Swizec/useAuth#34]
Hi, according to my understanding, `useEffect` should have **all** the variables listed in its `dependency list`, but it seems this line of code https://github.com/Swizec/useAuth/blob/master/src/AuthProvider.js#L53 does **not** include `contextValue` in the dependency list. 

The current code:

```javascript
useEffect(() => {
        setContextValue({ ...contextValue, state });
    }, [state]);
```

Maybe it's better this way?

```javascript
useEffect(() => {
        setContextValue((contextValue) => {
            return { ...contextValue, state };
        });
    }, [state]);
```

This allows us not to include `contextValue` into the dependency list. So we can follow the React Hooks rules.

**Comment by Swizec** [comment]
You are right. Thanks for pointing that out, have made that mistake in many projects :)

**Comment by Swizec** [comment]
@all-contributors add @sophister for bugs
