### ISSUE TITLE
Would you add a next.js example for useAuth?

### ISSUE THREAD

**Issue by stanxii** [Swizec/useAuth#36]
Thans a lot, I want a feature to use useAuth with next.js, But I am new for it. Would you out a next.js example for useAuth? thanks a lot. I will test it.

**Comment by duncanleung** [comment]
@stanxii Check out the open PR #35 (Nextjs example for react-use-auth).

You might get some ideas from it.

**Comment by Swizec** [comment]
Great suggestion @stanxii. Looks like @smehdii already took it on. Small bug right now but the basics seem to work.

Gonna merge and make official as soon as I can :)

**Comment by r3tard3dd** [comment]
@Swizec any news ?
