### ISSUE TITLE
Losing user

### ISSUE THREAD

**Issue by samullman** [Swizec/useAuth#77]
Very momentarily our User comes through

<img width="300" alt="Screen Shot 2020-05-09 at 1 08 31 PM" src="https://user-images.githubusercontent.com/10147333/81483917-6aeb2880-91f6-11ea-909a-738efbcd4198.png">

Followed by

<img width="300" alt="Screen Shot 2020-05-09 at 1 08 17 PM" src="https://user-images.githubusercontent.com/10147333/81483929-7f2f2580-91f6-11ea-8eea-93a45251657a.png">

Console

<img width="520" alt="Screen Shot 2020-05-09 at 1 09 52 PM" src="https://user-images.githubusercontent.com/10147333/81483952-a5ed5c00-91f6-11ea-82b9-3b5b5cb6dc23.png">

**Comment by samullman** [comment]
Solved this by going to Auth0 settings and adding "account" to allowed origin

**Comment by walberty** [comment]
@samullman I'm having the same problem but haven't been able to solve it. Can you clarify what you changed in the Auth0 settings? I'm not sure I'm looking at the same origin settings page.

**Comment by samullman** [comment]
@walberty 

Under application settings I changed:
<img width="669" alt="Screen Shot 2020-05-19 at 7 17 43 AM" src="https://user-images.githubusercontent.com/10147333/82337654-e1c7b480-99a0-11ea-88e6-af42eccc358d.png">
<img width="657" alt="Screen Shot 2020-05-19 at 7 17 24 AM" src="https://user-images.githubusercontent.com/10147333/82337672-e5f3d200-99a0-11ea-9827-7d6a9d3c8551.png">
