### ISSUE TITLE
Does this support Firebase Auth?

### ISSUE THREAD

**Issue by catrawalkar** [Swizec/useAuth#80]
Hello, I think I heard you say this hook supports Firebase Authentication too in yesterday's stream. Can you point me towards a resource or documentation about using Firebase Auth with this?

If successful, I would love to send an example as a PR

**Comment by catrawalkar** [comment]
Alright, I got answer to my question. Firebase Auth is not yet implemented.

**Comment by landsman** [comment]
I had same question.

**Comment by babycourageous** [comment]
@landsman I was poking around this library with a similar question and looks like it's in v1 with docs on the way
See https://github.com/Swizec/useAuth/issues/102

**Comment by Swizec** [comment]
@babycourageous @landsman with v2, just released, we now have the ability to add other providers. Any interest in writing a wrapper for Firebase?

**Comment by babycourageous** [comment]
Hi @Swizec
Thanks for the info!
I'm not too familiar with Firebase - but if I get some time to devote to it I can give it a shot.

**Comment by landsman** [comment]
@Swizec nice, thanks, for sure.

**Comment by Swizec** [comment]
@babycourageous @landsman I have a PR up with beta support for Firebase Auth. Since I'm not a Firebase user it's hard to make sure I got the DX right. Mind giving it a shot?

https://github.com/Swizec/useAuth/pull/148

**Comment by babycourageous** [comment]
@Swizec That's super awesome of ya! 
I'm also not a Firebase user unfortunately.

I'll try to find some time to familiarize myself with Firebase stuff and see if I can't take a peek at the DX sometime soon.
