### ISSUE TITLE
Use app_metadata for roles

### ISSUE THREAD

**Issue by mtt87** [Swizec/useAuth#81]
I think there is a security issue with this approach https://github.com/Swizec/useAuth#set-up-a-auth0-rule you are using `user_metadata` to store roles but a user could potentially change that. 

Auth0 recommends to use `app_metadata` as the right place to store user roles as that's not supposed to be editable by a user.
https://auth0.com/docs/users/concepts/overview-user-metadata

**Comment by IdentityDan** [comment]
In this instance, roles aren't being stored in the user_metadata object in Auth0, they are just using the user_metadata claim in the token which would be signed by the time it got to the user.

With that said, our guidance shows roles being added to the token in their own custom claim.
https://auth0.com/docs/authorization/concepts/sample-use-cases-rules#add-user-roles-to-tokens

**Comment by mtt87** [comment]
Thanks @IdentityDan , it was confusing to see the same key `user_metadata` but I understood your explanation in that case it's 🆗 👍
