### ISSUE TITLE
How to set the AuthProvider to the root component in the nextJS application?

### ISSUE THREAD

**Issue by chenxeed** [Swizec/useAuth#9]
Hi @Swizec , first of all, thank you for the library!

May I ask if it's compatible to be used in Next application as well?

> I recommend adding this around your root component.

I was stuck on how to set up the Auth Provider in the Next environment as you suggested above. Thanks!

**Comment by puregarlic** [comment]
@chenxeed Not sure if you figured out how to do this yet, but I ended up putting the `AuthProvider` component in `_app.js`, which is working well for me so far.

**Comment by chenxeed** [comment]
Hi @puregarlic , yes thanks! I've figured out my error.

If I try to access the context directly on the same component that has the `AuthProvider` like this:

(doesn't work)
```tsx
export default () => {
  const { user } = useAuth()
  // doesn't work as user is still the default value
  return <AuthProvider>
    <div>{ user.name }</div>
  </AuthProvider>
}
```

But if I wrap it as a child component, then it works:

```tsx
const Child = () => {
  const { user } = useAuth()
  return <div>{ user.name }</div>
}

export default () => {
  // doesn't work as user is still the default value
  return <AuthProvider>
    <Child/>
  </AuthProvider>
}
```

**Comment by Swizec** [comment]
@all-contributors add @puregarlic for question

**Comment by Swizec** [comment]
By the way @chenxeed the reason your original approach didn't work is because React context is only defined in the children of the provider. The component where you render `AuthProvider` (or any context provider) doesn't have access to that same context.

Something like this would have worked:

```javascript
export default () => {
  // doesn't work as user is still the default value
  return <AuthProvider>{() => {
      const { user } = useAuth()
    return (<div>{ user.name }</div>)
 }}</AuthProvider>
}
```
